# Generated by Django 5.2.5 on 2025-09-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('imagen', models.URLField(blank=True)),
                ('etiquetas', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
