# Generated by Django 5.2.5 on 2025-09-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINISTRADORES', '0001_initial'),
        ('ESTUDIANTES', '0001_initial'),
        ('PUBLICACIONES', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ADMINISTRADORES.administrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTES.estudiante'),
        ),
    ]
